POST http://localhost:8000/register HTTP/1.1
content-Type: application/json

{
  "username": "milon123",
  "password": "Milon@786",
  "email": "milon@gmail.com",
  "name": "Mirjaj Ajij Milon"
}

###

POST http://localhost:8000/register HTTP/1.1
content-Type: application/json

{
  "username": "Mirjaj@123",
  "password": "Mirjaj@786",
  "email": "Mirjaj@gmail.com",
  "name": "Mirjaj Ajij Milon"
}


###

POST http://localhost:8000/login HTTP/1.1
Content-Type: application/json

{
  "email": "milon@gmail.com",
  "password": "Milon@786"
}
###
POST http://localhost:8000/login HTTP/1.1
Content-Type: application/json

{
  "email": "Mirjaj@gmail.com",
  "password": "Mirjaj@786"
}

###
GET http://localhost:8000/get_user_and_profile HTTP/1.1
Content-Type: application/json

{
  "token":"de52ec362362d41dec004955a14a2ff84dc5bea6e642932ddbac5ee022e4c240dd2d"
}

###

POST http://localhost:8000/update_profile_data HTTP/1.1
Content-Type: application/json

{
  "token":"de52ec362362d41dec004955a14a2ff84dc5bea6e642932ddbac5ee022e4c240dd2d",
  "bio": "Passionate technology leader with expertise in cloud computing, software architecture, and team management. Dedicated to building scalable products and mentoring young developers.",
  "currentPost": "CTO",
  "pastWork": [
    {
      "company": "Microsoft",
      "position": "CTO",
      "years": "2+"
    }
  ],
  "education": [
    {
      "school": "IIT",
      "degree": "B.Tech",
      "fieldOfStudy": "2015-2019"
    }
  ]
}
###
GET http://localhost:8000/user/get_all_user_profile 